//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1087 with alias "navigation"
	/// <summary>Navigation</summary>
	public partial interface INavigation : IPublishedContent
	{
		/// <summary>Expansion Header Only</summary>
		bool ExpansionHeaderOnly { get; }

		/// <summary>Hide on Menu</summary>
		bool HideOnMenu { get; }
	}

	/// <summary>Navigation</summary>
	[PublishedContentModel("navigation")]
	public partial class Navigation : PublishedContentModel, INavigation
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "navigation";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Navigation(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Navigation, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Expansion Header Only: Only used in menu, no content for this page.
		///</summary>
		[ImplementPropertyType("expansionHeaderOnly")]
		public bool ExpansionHeaderOnly
		{
			get { return GetExpansionHeaderOnly(this); }
		}

		/// <summary>Static getter for Expansion Header Only</summary>
		public static bool GetExpansionHeaderOnly(INavigation that) { return that.GetPropertyValue<bool>("expansionHeaderOnly"); }

		///<summary>
		/// Hide on Menu
		///</summary>
		[ImplementPropertyType("hideOnMenu")]
		public bool HideOnMenu
		{
			get { return GetHideOnMenu(this); }
		}

		/// <summary>Static getter for Hide on Menu</summary>
		public static bool GetHideOnMenu(INavigation that) { return that.GetPropertyValue<bool>("hideOnMenu"); }
	}
}
